### PR TITLE
cluster specific settings for my.cnf and client packages

### PR DESCRIPTION
**Pull request by jklare**
- install percona-xtradb-cluster-client when percona.server.role includes "cluster"
- fixed check for percona.server.role when determining which template to use for my.cnf

### CODE REVIEW

**Comment by phlipper** [comment]
@jklare thank you very much for this! I will be happy to merge this, but first, please rebase on top of the latest master, and update the README with the new attribute assignment. Thanks!

**Comment by jharley** [comment]
This PR changes the way that a 'cluster' role has always been set and conflicts with the instructions on using PXC in the README.  Having 'role' be an array in a PXC deployment doesn't make sense in the context of the cookbook, as a PXC node has one role (a member of the cluster).

**Comment by jklare** [comment]
I agree with jharley and think role should be string. The reason why i switched to an array is this 5b75d47c6a602fa9ebffabeed2c4d23d3bab1aa9 commit.

**Comment by jharley** [comment]
I understand why a node having two roles in a ring-replication/multi-master setup makes sense, but am unsure how to handle this going forward as this more or less breaks previous attribute configurations for anyone using PXC.

Reverting your change to ```configure_server.rb``` and switching the logic on your if statement in ```client.rb``` to include a test for an array and the string check might be the safest if we want to not break the way things have been.

If the road forward is to define the role as an array, maybe a version bump and a log (panic?) to check for role being defined as a string is the way to go?

**Comment by jklare** [comment]
rebased and switched logic to allow array or string for server['role']

**Comment by phlipper** [comment]
@jklare thank you very much for this! I have rebased it on top of the latest master and merged it in as #318.

**Pull request closed without merging**
