### PR TITLE
Provider superclass mismatch fix

### PR DESCRIPTION
**Pull request by cybermerc**
Addresses issue #266 by adding percona subclass and cleaning up naming concerns.
Also added documentation to README on how to best utilize libraries.

### CODE REVIEW

**Comment by gravesb** [comment]
The resources are already provided in the mysql/mysql2_chef_gem cookbooks. Why copy them into this cookbook?  Is that just so consumers of this don't have to pull in either of those cookbooks?

One thing those cookbooks provide that isn't done here is the chefspec matcher.

**Comment by cybermerc** [comment]
@gravesb yeah felt like a few extra lines was better than two additional recipe dependencies. Really up to the maintainers, would be happy to remove the resources and add documentation to remind about the dependencies if that is preferred.

Totally missed the matchers.rb file though so added it in.

**Comment by gravesb** [comment]
IMO, I like what they did in the [database cookbook](https://github.com/opscode-cookbooks/database#resourcesproviders) and document that consumers need to select their preferred client library.  But yeah, I'm interested to see what the maintainers think.

**Comment by cybermerc** [comment]
After thinking over some of the possible complications I have removed the resource and matcher files. There could be some complications if you try and utilize this cookbook with the database cookbook. This should now work as expected, I have added some documentation to the README to make it clearer about the needs for the dependencies.

**Comment by gravesb** [comment]
+1

**Comment by wubrg** [comment]
+1

**Comment by stottsan** [comment]
:+1:

**Comment by martinb3** [comment]
:+1:

**Comment by jklare** [comment]
+1

**Comment by ajardan** [comment]
Hello guys!
Are there plans to merge this ? Looks like this fixes a pretty common issue, I am blocked for a couple of days myself.

Please let me know if there's anything I can help with to get this merged asap.

**Comment by mstyne** [comment]
:+1:

**Comment by ajardan** [comment]
@phlipper

**Comment by phlipper** [comment]
@cybermerc thank you very much for this! I have rebased it on top of the latest master and merged it in as #297.

**Comment by ajardan** [comment]
@phlipper thanks a lot for the merge !

**Pull request closed without merging**
