### PR TITLE
Install and configure pam_auth

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by Sauraus** [comment]
Any chance of getting this merged?

**Comment by phlipper** [comment]
@Sauraus yes, this will be merged, but it doesn't actually work correctly at the moment. I have started adding an integration test and fixing the missing bits, but I've also been sick for a little bit and haven't had as much time as I would like to get it wrapped up. Support is in progress and will be merged, but I don't have a hard date at the moment, sorry.

**Comment by Sauraus** [comment]
@phlipper thanks for the update and get well. :)

**Comment by Sauraus** [comment]
Any update on the merge?

**Comment by Sauraus** [comment]
Buehler? :(

**Comment by phlipper** [comment]
@Sauraus I'm sorry for the delay. I still have not had a chance to get this branch fully working yet. I would be happy to merge this if you are able to update this with working integration tests. If I am able to get a chance to get things working, I will merge it in then as well. This isn't a feature I use so other issues have taken priority.

**Pull request closed without merging**
